name: Run tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and test
        run: |
          npm ci
          npm run test --updateSnapshot
