name: Run tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and test
        run: |
          npm install
          CI=true npm run test --updateSnapshot
      - name: cypress tests
        uses: cypress-io/github-action@v2